name: ExigoGrid
favicon: null
layout_spectrum: 0
typography_spectrum: 0.25254
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#5fb772'
    - '#000000'
    - '#395da8'
    - '#bf2c38'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
