name: ExigoGrid
favicon: null
layout_spectrum: 0.9239060042891651
typography_spectrum: 0.135042144684121
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#19351a'
    - '#3f5441'
    - '#829184'
    - '#b2bfb4'
  brandStrength: 0.030487907119095325
  lightness: 0.7188590136356652
  saturation: 0.9966935676056892
  rhythmicContrast: 0.4975953185930848
purpose: []
